2023-01-17 15:46:29,564 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='www.sbi.co.in', port=443): Read timed out. (read timeout=5)")': /documents/16012/1400784/FOREX_CARD_RATES.pdf
2023-02-16 15:19:54,644 - root - ERROR - 
Traceback (most recent call last):
  File "/home/runner/work/sbi_forex_rates/sbi_forex_rates/main.py", line 69, in dump_data
    page_1_text, page_2_text = extract_text(file_content)
  File "/home/runner/work/sbi_forex_rates/sbi_forex_rates/main.py", line 43, in extract_text
    reader = PyPDF2.PdfReader(file_content, strict=False)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/PyPDF2/_reader.py", line 317, in __init__
    self.read(stream)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/PyPDF2/_reader.py", line 1409, in read
    self._find_eof_marker(stream)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/PyPDF2/_reader.py", line 1465, in _find_eof_marker
    raise PdfReadError("EOF marker not found")
PyPDF2.errors.PdfReadError: EOF marker not found
2023-02-18 15:18:17,364 - urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /documents/16012/1400784/FOREX_CARD_RATES.pdf
2023-02-18 15:18:24,369 - urllib3.connectionpool - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /documents/16012/1400784/FOREX_CARD_RATES.pdf
2023-02-18 15:18:25,835 - root - ERROR - 
Traceback (most recent call last):
  File "/home/runner/work/sbi_forex_rates/sbi_forex_rates/main.py", line 69, in dump_data
    page_1_text, page_2_text = extract_text(file_content)
  File "/home/runner/work/sbi_forex_rates/sbi_forex_rates/main.py", line 43, in extract_text
    reader = PyPDF2.PdfReader(file_content, strict=False)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/PyPDF2/_reader.py", line 317, in __init__
    self.read(stream)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/PyPDF2/_reader.py", line 1409, in read
    self._find_eof_marker(stream)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/PyPDF2/_reader.py", line 1465, in _find_eof_marker
    raise PdfReadError("EOF marker not found")
PyPDF2.errors.PdfReadError: EOF marker not found
2023-02-19 15:17:55,582 - urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /documents/16012/1400784/FOREX_CARD_RATES.pdf
2023-02-19 15:18:02,468 - urllib3.connectionpool - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /documents/16012/1400784/FOREX_CARD_RATES.pdf
2023-02-19 15:18:03,752 - root - ERROR - 
Traceback (most recent call last):
  File "/home/runner/work/sbi_forex_rates/sbi_forex_rates/main.py", line 81, in dump_data
    reader = PyPDF2.PdfReader(file_content, strict=False)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/PyPDF2/_reader.py", line 317, in __init__
    self.read(stream)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/PyPDF2/_reader.py", line 1409, in read
    self._find_eof_marker(stream)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/PyPDF2/_reader.py", line 1465, in _find_eof_marker
    raise PdfReadError("EOF marker not found")
PyPDF2.errors.PdfReadError: EOF marker not found
2023-03-01 15:20:51,008 - urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /documents/16012/1400784/FOREX_CARD_RATES.pdf
2023-03-01 15:20:52,461 - root - ERROR - 
Traceback (most recent call last):
  File "/home/runner/work/sbi_forex_rates/sbi_forex_rates/main.py", line 81, in dump_data
    reader = PyPDF2.PdfReader(file_content, strict=False)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/PyPDF2/_reader.py", line 317, in __init__
    self.read(stream)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/PyPDF2/_reader.py", line 1409, in read
    self._find_eof_marker(stream)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/PyPDF2/_reader.py", line 1465, in _find_eof_marker
    raise PdfReadError("EOF marker not found")
PyPDF2.errors.PdfReadError: EOF marker not found
2023-03-23 15:18:15,146 - urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /documents/16012/1400784/FOREX_CARD_RATES.pdf
2023-04-03 16:37:34,434 - urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /documents/16012/1400784/FOREX_CARD_RATES.pdf
2023-04-03 16:37:41,470 - urllib3.connectionpool - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /documents/16012/1400784/FOREX_CARD_RATES.pdf
2023-04-06 10:30:53,895 - urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /documents/16012/1400784/FOREX_CARD_RATES.pdf
2023-04-18 10:32:02,913 - urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='www.sbi.co.in', port=443): Read timed out. (read timeout=10)")': /documents/16012/1400784/FOREX_CARD_RATES.pdf
2023-05-04 16:44:20,229 - urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /documents/16012/1400784/FOREX_CARD_RATES.pdf
2023-05-27 10:31:08,993 - urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='www.sbi.co.in', port=443): Read timed out. (read timeout=10)")': /documents/16012/1400784/FOREX_CARD_RATES.pdf
